import glob
import os

env = Environment()

TARGET = 'test_particle.x'
program = env.Program(target = TARGET, source = 'test_particle.c', LIBS=['nbody', 'm'], LIBPATH='../lib')

env.Default(program)

Alias('program', program)